using System.Collections.Generic;
using System.IO;
using System.Text;
using NUnit.Framework;
using TypeUSS;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace TypeUSS.Tests
{
    /// <summary>
    /// Validates that every USS property the <see cref="StyleBuilder"/> emits is a real
    /// property that Unity's own USS importer accepts in THIS Unity version.
    ///
    /// This is the source of truth - the online docs drift between versions (they list
    /// transform/filter as unsupported even though they work), but the importer does not
    /// lie. The test builds a stylesheet exercising every wrapper, imports it through the
    /// AssetDatabase, and fails if the importer reports an unknown property or invalid
    /// value. Missing-asset warnings (e.g. for background-image references) are
    /// intentionally ignored - we validate property names and value syntax, not assets.
    ///
    /// MAINTENANCE: when you add a wrapper to StyleBuilder, add a representative call to
    /// <see cref="Exercise"/> below so the new property stays covered.
    /// </summary>
    public class UssPropertyValidationTests
    {
        private const string TempFolderName = "__TypeUSS_Validation__";
        private const string TempDir = "Assets/" + TempFolderName;
        private const string UssPath = TempDir + "/_validation.uss";

        // Case-insensitive substrings that indicate a genuine property/value problem.
        // Deliberately excludes asset-resolution noise ("cannot find", "could not load").
        private static readonly string[] FailureMarkers =
        {
            "unknown property",
            "invalid",
            "unsupported",
        };

        [Test]
        public void EveryWrappedProperty_IsAcceptedByUnityImporter()
        {
            var uss = BuildExerciseUss();

            if (!AssetDatabase.IsValidFolder(TempDir))
                AssetDatabase.CreateFolder("Assets", TempFolderName);
            File.WriteAllText(Path.GetFullPath(UssPath), uss);

            var problems = new List<string>();

            void Handler(string condition, string stackTrace, LogType type)
            {
                if (type == LogType.Log) return; // ignore informational logs
                var lower = condition.ToLowerInvariant();
                foreach (var marker in FailureMarkers)
                {
                    if (lower.Contains(marker))
                    {
                        problems.Add(condition);
                        break;
                    }
                }
            }

            Application.logMessageReceived += Handler;
            try
            {
                AssetDatabase.ImportAsset(UssPath,
                    ImportAssetOptions.ForceSynchronousImport | ImportAssetOptions.ForceUpdate);
            }
            finally
            {
                Application.logMessageReceived -= Handler;
            }

            // Sanity: the sheet must actually import as a StyleSheet.
            var sheet = AssetDatabase.LoadAssetAtPath<StyleSheet>(UssPath);
            Assert.IsNotNull(sheet, "Validation stylesheet failed to import as a StyleSheet asset.");

            Assert.IsEmpty(problems,
                "Unity's USS importer rejected one or more TypeUSS properties/values:\n  - " +
                string.Join("\n  - ", problems) +
                "\n\n--- Generated USS ---\n" + uss);
        }

        [TearDown]
        public void Cleanup()
        {
            if (AssetDatabase.IsValidFolder(TempDir))
                AssetDatabase.DeleteAsset(TempDir);
        }

        private static string BuildExerciseUss()
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* TypeUSS property validation - generated by tests */");
            sb.AppendLine();
            foreach (var style in Exercise())
            {
                sb.AppendLine(style.ToUSS());
                sb.AppendLine();
            }
            return sb.ToString();
        }

        /// <summary>
        /// One representative call for EVERY StyleBuilder wrapper, grouped into rules so a
        /// failure points at a small cluster. Values are kept self-contained (no real asset
        /// references, cursor uses a keyword) so the importer emits no missing-asset noise.
        /// </summary>
        private static IEnumerable<TypeStyle> Exercise()
        {
            yield return Sel.Class("sizing").Style(s => s
                .Width(100).Width(Length.Percent(50)).Width(Length.Auto)
                .Height(200).MinWidth(10).MinHeight(10).MaxWidth(500).MaxHeight(Length.Percent(80)));

            yield return Sel.Class("flex").Style(s => s
                .FlexDirection(FlexDirection.Row).FlexWrap(Wrap.Wrap)
                .FlexGrow(1).FlexShrink(0).FlexBasis(Length.Auto)
                .AlignItems(Align.Center).AlignSelf(Align.FlexStart).AlignContent(Align.Stretch)
                .JustifyContent(Justify.SpaceBetween));

            yield return Sel.Class("spacing").Style(s => s
                .Padding(10).Padding(10, 20).Padding(1, 2, 3, 4)
                .PaddingTop(1).PaddingRight(2).PaddingBottom(3).PaddingLeft(4)
                .Margin(10).Margin(10, 20).Margin(1, 2, 3, 4)
                .MarginTop(1).MarginRight(2).MarginBottom(3).MarginLeft(Length.Auto));

            yield return Sel.Class("position").Style(s => s
                .Position(Position.Absolute).Top(0).Right(0).Bottom(0).Left(0));

            yield return Sel.Class("background").Style(s => s
                .BackgroundImage("none")
                .BackgroundColor(new Color(0, 0, 0, 0.5f))
                .UnityBackgroundImageTintColor(Color.white)
                .UnityBackgroundImageTintColor("rgb(255, 255, 255)")
                .UnityBackgroundScaleMode("scale-to-fit")
                .BackgroundPosition(BackgroundPositionKeyword.Center, BackgroundPositionKeyword.Center)
                .BackgroundRepeat(Repeat.NoRepeat, Repeat.NoRepeat)
                .BackgroundSize(100, 100).BackgroundSize(Length.Percent(100), Length.Percent(100)));

            yield return Sel.Class("slice").Style(s => s
                .UnitySlice(12).UnitySlice(1, 2, 3, 4)
                .UnitySliceLeft(1).UnitySliceTop(2).UnitySliceRight(3).UnitySliceBottom(4)
                .UnitySliceScale(Length.Px(1)));

            yield return Sel.Class("color-border").Style(s => s
                .Color(Color.white).BorderColor(Color.gray)
                .BorderTopColor(Color.red).BorderRightColor(Color.red)
                .BorderBottomColor(Color.red).BorderLeftColor(Color.red)
                .BorderWidth(1).BorderTopWidth(1).BorderRightWidth(1)
                .BorderBottomWidth(1).BorderLeftWidth(1)
                .BorderRadius(4).BorderRadius(4, 8).BorderRadius(1, 2, 3, 4)
                .BorderTopLeftRadius(1).BorderTopRightRadius(2)
                .BorderBottomRightRadius(3).BorderBottomLeftRadius(4));

            yield return Sel.Class("display").Style(s => s
                .Display(DisplayStyle.Flex).Visibility(Visibility.Hidden)
                .Overflow(Overflow.Hidden).TextOverflow(TextOverflow.Ellipsis).Opacity(0.5f));

            yield return Sel.Class("text").Style(s => s
                .FontSize(14).FontSize(14f).LetterSpacing(2).WordSpacing(2).UnityParagraphSpacing(8)
                .UnityFontStyleAndWeight(FontStyle.Bold)
                .UnityTextAlign(TextAnchor.MiddleCenter)
                .UnityFontDefinition("initial")
                .WhiteSpace(WhiteSpace.Normal)
                .Cursor("text"));

            yield return Sel.Class("text-effects").Style(s => s
                .TextShadow(2, 2, 4, Color.black)
                .UnityTextOutlineWidth(1).UnityTextOutlineColor(Color.black)
                .UnityTextOutline(1, Color.black));

            yield return Sel.Class("transform").Style(s => s
                .Rotate(45f).Scale(1.5f).Scale(1.5f, 0.5f)
                .Translate(10, Length.Percent(50))
                .TransformOrigin(Length.Percent(50), Length.Percent(50)));

            yield return Sel.Class("transitions").Style(s => s
                .TransitionProperty("background-color", "opacity")
                .TransitionDuration(0.12f, 0.1f)
                .TransitionTimingFunction(EasingMode.EaseOut, EasingMode.Linear)
                .TransitionDelay(0.05f)
                .Transition("color", 0.2f, EasingMode.EaseInOut));

            // --unity-cursor-color is a custom property (variable); the importer accepts
            // any custom name, so this mainly guards the value-syntax helpers.
            yield return Sel.Class("caret").Style(s => s
                .UnityCursorColor(new Color(0.9f, 0.88f, 0.8f))
                .UnityCursorColor("rgb(230, 224, 204)"));
        }
    }
}
