using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using TypeUSS;
using UnityEngine;
using UnityEngine.UIElements;
using UnityEditor;

namespace TypeUSS.Editor
{
    public static class USSGenerator
    {
        private const string GeneratedHeader = "/* Auto-generated by TypeUSS - Do not edit manually */";

        public static List<string> GenerateAll()
        {
            var generatedFiles = new List<string>();
            var styleClasses = FindAllStyleClasses();

            foreach (var (type, attribute) in styleClasses)
            {
                try
                {
                    var ussContent = GenerateUSSForClass(type, attribute);
                    var outputPath = WriteUSSFile(attribute.OutputPath, ussContent);
                    generatedFiles.Add(outputPath);

                    Debug.Log($"[TypeUSS] Generated: {outputPath}");
                }
                catch (Exception ex)
                {
                    Debug.LogError($"[TypeUSS] Failed to generate USS for {type.FullName}: {ex.Message}\n{ex.StackTrace}");
                }
            }

            if (generatedFiles.Count > 0)
            {
                AssetDatabase.Refresh();
                EditorApplication.delayCall += () => UpdateStyleSheetReferences(generatedFiles);
            }

            return generatedFiles;
        }

        public static string GenerateUSSForClass(Type type, GenerateUSSAttribute attribute)
        {
            var styles = ExtractStyles(type);
            return BuildUSSContent(styles);
        }

        private static void UpdateStyleSheetReferences(List<string> generatedFiles)
        {
            // Build a dictionary of path -> StyleSheet
            var pathToSheet = new Dictionary<string, StyleSheet>();

            foreach (var path in generatedFiles)
            {
                var sheet = AssetDatabase.LoadAssetAtPath<StyleSheet>(path);
                if (sheet != null)
                {
                    // Normalize path for comparison
                    var normalizedPath = path.Replace("\\", "/");
                    if (normalizedPath.StartsWith("Assets/"))
                        normalizedPath = normalizedPath.Substring("Assets/".Length);
                    pathToSheet[normalizedPath] = sheet;
                }
                else
                {
                    Debug.LogWarning($"[TypeUSS] Could not load StyleSheet at {path}");
                }
            }

            if (pathToSheet.Count == 0) return;

            // Find all MonoBehaviours with a StyleSheet[] field
            var consumers = FindStyleSheetConsumers();

            foreach (var (monoBehaviour, field, pathAttribute) in consumers)
            {
                List<StyleSheet> sheetsToAssign;

                if (pathAttribute != null && pathAttribute.PathPrefixes.Length > 0)
                {
                    // Filter by path prefixes
                    sheetsToAssign = pathToSheet
                        .Where(kvp => pathAttribute.PathPrefixes.Any(prefix =>
                            kvp.Key.StartsWith(prefix.Replace("\\", "/"), StringComparison.OrdinalIgnoreCase)))
                        .Select(kvp => kvp.Value)
                        .ToList();
                }
                else
                {
                    // No filter - include all stylesheets
                    sheetsToAssign = pathToSheet.Values.ToList();
                }

                field.SetValue(monoBehaviour, sheetsToAssign.ToArray());
                EditorUtility.SetDirty(monoBehaviour);
                Debug.Log($"[TypeUSS] Updated {monoBehaviour.GetType().Name} with {sheetsToAssign.Count} stylesheets" +
                    (pathAttribute != null ? $" (filtered by: {string.Join(", ", pathAttribute.PathPrefixes)})" : ""));
            }
        }

        private static List<(MonoBehaviour mono, FieldInfo field, StyleSheetPathAttribute pathAttr)> FindStyleSheetConsumers()
        {
            var results = new List<(MonoBehaviour, FieldInfo, StyleSheetPathAttribute)>();

            // Search in all open scenes
            for (int i = 0; i < UnityEngine.SceneManagement.SceneManager.sceneCount; i++)
            {
                var scene = UnityEngine.SceneManagement.SceneManager.GetSceneAt(i);
                if (!scene.isLoaded) continue;

                foreach (var root in scene.GetRootGameObjects())
                {
                    foreach (var mb in root.GetComponentsInChildren<MonoBehaviour>(true))
                    {
                        if (mb == null) continue;

                        var field = mb.GetType().GetField("styleSheets", BindingFlags.NonPublic | BindingFlags.Instance);
                        if (field != null && field.FieldType == typeof(StyleSheet[]))
                        {
                            var pathAttr = field.GetCustomAttribute<StyleSheetPathAttribute>();
                            results.Add((mb, field, pathAttr));
                        }
                    }
                }
            }

            return results;
        }

        private static IEnumerable<(Type type, GenerateUSSAttribute attr)> FindAllStyleClasses()
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic &&
                            !a.FullName.StartsWith("System") &&
                            !a.FullName.StartsWith("Microsoft") &&
                            !a.FullName.StartsWith("Unity.") &&
                            !a.FullName.StartsWith("UnityEngine") &&
                            !a.FullName.StartsWith("UnityEditor") &&
                            !a.FullName.StartsWith("mscorlib") &&
                            !a.FullName.StartsWith("netstandard"))
                .SelectMany(a =>
                {
                    try { return a.GetTypes(); }
                    catch { return Array.Empty<Type>(); }
                })
                .Select(t => (type: t, attr: t.GetCustomAttribute<GenerateUSSAttribute>()))
                .Where(x => x.attr != null);
        }

        private static List<TypeStyle> ExtractStyles(Type type)
        {
            var styles = new List<TypeStyle>();

            var styleFields = type.GetFields(BindingFlags.Public | BindingFlags.Static)
                .Where(f => f.FieldType == typeof(TypeStyle));

            foreach (var field in styleFields)
            {
                try
                {
                    var style = (TypeStyle)field.GetValue(null);
                    if (style != null)
                    {
                        styles.Add(style);
                    }
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"[TypeUSS] Could not extract style from {type.Name}.{field.Name}: {ex.Message}");
                }
            }

            var styleProperties = type.GetProperties(BindingFlags.Public | BindingFlags.Static)
                .Where(p => p.PropertyType == typeof(TypeStyle) && p.CanRead);

            foreach (var prop in styleProperties)
            {
                try
                {
                    var style = (TypeStyle)prop.GetValue(null);
                    if (style != null)
                    {
                        styles.Add(style);
                    }
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"[TypeUSS] Could not extract style from {type.Name}.{prop.Name}: {ex.Message}");
                }
            }

            return styles;
        }

        private static string BuildUSSContent(List<TypeStyle> styles)
        {
            var sb = new StringBuilder();

            sb.AppendLine(GeneratedHeader);
            sb.AppendLine();

            foreach (var style in styles)
            {
                sb.AppendLine(style.ToUSS());
                sb.AppendLine();
            }

            return sb.ToString().TrimEnd();
        }

        private static string WriteUSSFile(string relativePath, string content)
        {
            if (!relativePath.StartsWith("Assets/") && !relativePath.StartsWith("Assets\\"))
            {
                relativePath = Path.Combine("Assets", relativePath);
            }

            if (!relativePath.EndsWith(".uss", StringComparison.OrdinalIgnoreCase))
            {
                relativePath += ".uss";
            }

            relativePath = relativePath.Replace("\\", "/");

            var fullPath = Path.GetFullPath(relativePath);
            var directory = Path.GetDirectoryName(fullPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(fullPath))
            {
                var existingContent = File.ReadAllText(fullPath);
                if (existingContent == content)
                {
                    return relativePath;
                }
            }

            File.WriteAllText(fullPath, content);
            return relativePath;
        }
    }
}
